/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author leahm
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDigits8 = new javax.swing.JButton();
        jbtnDigits7 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDigits9 = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnDigits6 = new javax.swing.JButton();
        jbtnDigits4 = new javax.swing.JButton();
        jbtnDigits5 = new javax.swing.JButton();
        jbtnDigits7Multiply = new javax.swing.JButton();
        jbtnDigits3 = new javax.swing.JButton();
        jbtnDigits1 = new javax.swing.JButton();
        jbtnDigits2 = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jbtnDecimal = new javax.swing.JButton();
        jbtnDigits0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 50));

        jbtnCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, 50));

        jbtnBS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 50));

        jbtnDivide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDivide.setText("/");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 74, 50));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 70, 50));

        jbtnDigits8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits8.setText("8");
        jbtnDigits8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, 50));

        jbtnDigits7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits7.setText("7");
        jbtnDigits7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 50));

        jbtnPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 70, 50));

        jbtnDigits9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits9.setText("9");
        jbtnDigits9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 50));

        jbtnMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnMinus.setText("-");
        getContentPane().add(jbtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 70, 50));

        jbtnDigits6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits6.setText("6");
        jbtnDigits6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 70, 50));

        jbtnDigits4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits4.setText("4");
        jbtnDigits4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 50));

        jbtnDigits5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits5.setText("5");
        jbtnDigits5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 70, 50));

        jbtnDigits7Multiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits7Multiply.setText("*");
        getContentPane().add(jbtnDigits7Multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 70, 50));

        jbtnDigits3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits3.setText("3");
        jbtnDigits3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 50));

        jbtnDigits1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits1.setText("1");
        jbtnDigits1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 50));

        jbtnDigits2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits2.setText("2");
        jbtnDigits2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, 50));

        jbtnEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 70, 50));

        jbtnDecimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDecimal.setText(".");
        jbtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 70, 50));

        jbtnDigits0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigits0.setText("0");
        jbtnDigits0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigits0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigits0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers(String q)
    {
        String Nums =jtxtResult.getText()+ q;
        jtxtResult.setText(Nums);
    }
    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDigits9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits9ActionPerformed
         EnterNumbers("9");
    }//GEN-LAST:event_jbtnDigits9ActionPerformed

    private void jbtnDigits6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnDigits6ActionPerformed

    private void jbtnDigits3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnDigits3ActionPerformed

    private void jbtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecimalActionPerformed
      if(! jtxtResult.getText().contains("."))
      {
          jtxtResult.setText(jtxtResult.getText() + jbtnDecimal.getText());
      }
    }//GEN-LAST:event_jbtnDecimalActionPerformed

    private void jbtnDigits7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits7ActionPerformed
      EnterNumbers("7");
    }//GEN-LAST:event_jbtnDigits7ActionPerformed

    private void jbtnDigits8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnDigits8ActionPerformed

    private void jbtnDigits4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnDigits4ActionPerformed

    private void jbtnDigits5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits5ActionPerformed
         EnterNumbers("5");
    }//GEN-LAST:event_jbtnDigits5ActionPerformed

    private void jbtnDigits2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits2ActionPerformed
         EnterNumbers("2");
    }//GEN-LAST:event_jbtnDigits2ActionPerformed

    private void jbtnDigits1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits1ActionPerformed
       EnterNumbers("1");
    }//GEN-LAST:event_jbtnDigits1ActionPerformed

    private void jbtnDigits0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigits0ActionPerformed
         EnterNumbers("0");
    }//GEN-LAST:event_jbtnDigits0ActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
       NumEnter1 = Double.parseDouble(jtxtResult.getText());
       jtxtResult.setText("");
       op ="/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
         NumEnter1 = Double.parseDouble(jtxtResult.getText());
       jtxtResult.setText("");
       op ="+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        
       String Fn,Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn ="";
        Sn ="";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
       String backSp = null;
       
       if(jtxtResult.getText().length() > 0)
       {
           StringBuilder sb = new StringBuilder(jtxtResult.getText());
           sb.deleteCharAt(jtxtResult.getText().length() - 1);
           backSp = sb.toString();
           jtxtResult.setText(backSp);
       }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        if(op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if(op == "-")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        if(op == "*")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        if(op == "/")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDecimal;
    private javax.swing.JButton jbtnDigits0;
    private javax.swing.JButton jbtnDigits1;
    private javax.swing.JButton jbtnDigits2;
    private javax.swing.JButton jbtnDigits3;
    private javax.swing.JButton jbtnDigits4;
    private javax.swing.JButton jbtnDigits5;
    private javax.swing.JButton jbtnDigits6;
    private javax.swing.JButton jbtnDigits7;
    private javax.swing.JButton jbtnDigits7Multiply;
    private javax.swing.JButton jbtnDigits8;
    private javax.swing.JButton jbtnDigits9;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
